sudo: required
services:
  - docker

before_install:
  - docker build -t devspeter/react-docker -f Dockerfile.dev .

script:
  - docker run devspeter/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'react-docker'
  env: 'ReactDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-484944426529'
  bucket_path: 'react-docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
